import type { IconType } from "react-icons";
import {
  FiActivity,
  FiArrowRight,
  FiAward,
  FiBook,
  FiBookOpen,
  FiCalendar,
  FiCheckCircle,
  FiCircle,
  FiClock,
  FiCode,
  FiCpu,
  FiDatabase,
  FiDownload,
  FiExternalLink,
  FiGitBranch,
  FiGithub,
  FiGlobe,
  FiKey,
  FiLayers,
  FiLayout,
  FiLink,
  FiLinkedin,
  FiMail,
  FiMapPin,
  FiMenu,
  FiMoon,
  FiSettings,
  FiShare2,
  FiShield,
  FiShuffle,
  FiSend,
  FiStar,
  FiSun,
  FiTerminal,
  FiX,
  FiZap,
} from "react-icons/fi";
import {
  SiAxios,
  SiBootstrap,
  SiCss,
  SiDatadog,
  SiDotnet,
  SiFluentbit,
  SiFramer,
  SiGit,
  SiGithub,
  SiGitkraken,
  SiHtml5,
  SiInsomnia,
  SiJavascript,
  SiJsonwebtokens,
  SiMaildotru,
  SiMui,
  SiPostman,
  SiReact,
  SiReactquery,
  SiReactrouter,
  SiRedis,
  SiRedux,
  SiSharp,
  SiSwagger,
  SiTailwindcss,
  SiTypescript,
  SiVite,
} from "react-icons/si";
import {
  MdOutlineCalendarToday,
  MdOutlineCategory,
  MdOutlineCheck,
  MdOutlineClose,
  MdOutlineContentCopy,
  MdOutlinePerson,
  MdOutlineSecurity,
  MdVerified,
} from "react-icons/md";
import { CgWebsite } from "react-icons/cg";

export type IconEntry =
  | { type: "react"; component: IconType; className?: string }
  | { type: "devicon"; className: string };

const dev = (className: string): IconEntry => ({ type: "devicon", className });

const reactIcon = (component: IconType, className?: string): IconEntry =>
  className === undefined
    ? { type: "react", component }
    : { type: "react", component, className };

export const iconMap: Record<string, IconEntry> = {
  // ---- universal UI icons ----
  FiActivity: reactIcon(FiActivity),
  FiArrowRight: reactIcon(FiArrowRight),
  FiAward: reactIcon(FiAward),
  FiBook: reactIcon(FiBook),
  FiBookOpen: reactIcon(FiBookOpen),
  FiCalendar: reactIcon(FiCalendar),
  FiCheckCircle: reactIcon(FiCheckCircle),
  FiCircle: reactIcon(FiCircle),
  FiClock: reactIcon(FiClock),
  FiCode: reactIcon(FiCode),
  FiCpu: reactIcon(FiCpu),
  FiDatabase: reactIcon(FiDatabase),
  FiDownload: reactIcon(FiDownload),
  FiExternalLink: reactIcon(FiExternalLink),
  FiGitBranch: reactIcon(FiGitBranch),
  FiGithub: reactIcon(FiGithub),
  FiGlobe: reactIcon(FiGlobe),
  FiKey: reactIcon(FiKey),
  FiLayers: reactIcon(FiLayers),
  FiLayout: reactIcon(FiLayout),
  FiLink: reactIcon(FiLink),
  FiLinkedin: reactIcon(FiLinkedin),
  FiMail: reactIcon(FiMail),
  FiMapPin: reactIcon(FiMapPin),
  FiMenu: reactIcon(FiMenu),
  FiMoon: reactIcon(FiMoon),
  FiSettings: reactIcon(FiSettings),
  FiShare2: reactIcon(FiShare2),
  FiShield: reactIcon(FiShield),
  FiShuffle: reactIcon(FiShuffle),
  FiSend: reactIcon(FiSend),
  FiStar: reactIcon(FiStar),
  FiSun: reactIcon(FiSun),
  FiTerminal: reactIcon(FiTerminal),
  FiX: reactIcon(FiX),
  FiZap: reactIcon(FiZap),
  SiAxios: reactIcon(SiAxios),
  SiBootstrap: reactIcon(SiBootstrap),
  SiCss: reactIcon(SiCss),
  SiDatadog: reactIcon(SiDatadog),
  SiDotnet: reactIcon(SiDotnet),
  SiFluentbit: reactIcon(SiFluentbit),
  SiFramer: reactIcon(SiFramer),
  SiGit: reactIcon(SiGit),
  SiGithub: reactIcon(SiGithub),
  SiGitkraken: reactIcon(SiGitkraken),
  SiHtml5: reactIcon(SiHtml5),
  SiInsomnia: reactIcon(SiInsomnia),
  SiJavascript: reactIcon(SiJavascript),
  SiJsonwebtokens: reactIcon(SiJsonwebtokens),
  SiMaildotru: reactIcon(SiMaildotru),
  SiMui: reactIcon(SiMui),
  SiPostman: reactIcon(SiPostman),
  SiReact: reactIcon(SiReact),
  SiReactquery: reactIcon(SiReactquery),
  SiReactrouter: reactIcon(SiReactrouter),
  SiRedis: reactIcon(SiRedis),
  SiRedux: reactIcon(SiRedux),
  SiSharp: reactIcon(SiSharp),
  SiSwagger: reactIcon(SiSwagger),
  SiTailwindcss: reactIcon(SiTailwindcss),
  SiTypescript: reactIcon(SiTypescript),
  SiVite: reactIcon(SiVite),
  MdOutlineCalendarToday: reactIcon(MdOutlineCalendarToday),
  MdOutlineCategory: reactIcon(MdOutlineCategory),
  MdOutlineCheck: reactIcon(MdOutlineCheck),
  MdOutlineClose: reactIcon(MdOutlineClose),
  MdOutlineContentCopy: reactIcon(MdOutlineContentCopy),
  MdOutlinePerson: reactIcon(MdOutlinePerson),
  MdOutlineSecurity: reactIcon(MdOutlineSecurity),
  MdVerified: reactIcon(MdVerified),
  CgWebsite: reactIcon(CgWebsite),

  // ---- skill icons (by id, devicon) ----
  dotnet: dev("devicon-dotnetcore-plain colored"),
  "aspnet-core": dev("devicon-dotnetcore-plain colored"),
  csharp: dev("devicon-csharp-plain colored"),
  "ef-core": dev("devicon-entityframeworkcore-plain colored"),
  "sql-server": dev("devicon-microsoftsqlserver-plain colored"),
  redis: dev("devicon-redis-plain colored"),
  identity: dev("devicon-dotnetcore-plain colored"),
  automapper: dev("devicon-dotnetcore-plain colored"),
  mapster: dev("devicon-dotnetcore-plain colored"),
  react: dev("devicon-react-original colored"),
  typescript: dev("devicon-typescript-plain colored"),
  javascript: dev("devicon-javascript-plain colored"),
  html5: dev("devicon-html5-plain colored"),
  css3: dev("devicon-css3-plain colored"),
  tailwind: dev("devicon-tailwindcss-plain colored"),
  bootstrap: dev("devicon-bootstrap-plain colored"),
  "redux-toolkit": dev("devicon-redux-original colored"),
  vite: dev("devicon-vitejs-plain colored"),
  "visual-studio": dev("devicon-visualstudio-plain colored"),
  vscode: dev("devicon-vscode-plain colored"),
  git: dev("devicon-git-plain colored"),
  github: dev("devicon-github-plain colored"),
  postman: dev("devicon-postman-plain colored"),
  swagger: dev("devicon-swagger-plain colored"),
  ssms: dev("devicon-azuresqldatabase-plain colored"),
  "redis-insight": dev("devicon-redis-plain colored"),

  // ---- skill icons (by id, no devicon -> react-icons) ----
  "rest-api": reactIcon(SiInsomnia, "text-[#4000BF] dark:text-[#9A86FF]"),
  mailkit: reactIcon(SiMaildotru, "text-[#30302E] dark:text-slate-200"),
  mui: reactIcon(SiMui, "text-[#007FFF] dark:text-[#64B5F6]"),
  "react-query": reactIcon(SiReactquery, "text-[#FF4154] dark:text-[#FF6B7A]"),
  "react-router": reactIcon(SiReactrouter, "text-[#CA4245] dark:text-[#E57373]"),
  "framer-motion": reactIcon(SiFramer, "text-[#0055FF] dark:text-[#7AA2FF]"),
  gitkraken: reactIcon(SiGitkraken, "text-[#179287] dark:text-[#5FCBC0]"),
  jwt: reactIcon(FiKey, "text-teal-700 dark:text-primary"),
  fluentvalidation: reactIcon(FiCheckCircle, "text-teal-700 dark:text-primary"),
  serilog: reactIcon(FiTerminal, "text-teal-700 dark:text-primary"),

  // ---- display-name aliases (skills + project techs, devicon) ----
  ".NET": dev("devicon-dotnetcore-plain colored"),
  "ASP.NET Core": dev("devicon-dotnetcore-plain colored"),
  "C#": dev("devicon-csharp-plain colored"),
  "Entity Framework Core": dev("devicon-entityframeworkcore-plain colored"),
  "SQL Server": dev("devicon-microsoftsqlserver-plain colored"),
  Redis: dev("devicon-redis-plain colored"),
  Mapster: dev("devicon-dotnetcore-plain colored"),
  React: dev("devicon-react-original colored"),
  TypeScript: dev("devicon-typescript-plain colored"),
  JavaScript: dev("devicon-javascript-plain colored"),
  HTML: dev("devicon-html5-plain colored"),
  CSS: dev("devicon-css3-plain colored"),
  "Tailwind CSS": dev("devicon-tailwindcss-plain colored"),
  Bootstrap: dev("devicon-bootstrap-plain colored"),
  "Redux Toolkit": dev("devicon-redux-original colored"),
  "REST APIs": dev("devicon-fastapi-plain"),
  "React Query": dev("devicon-tailwindcss-plain"),
  Vite: dev("devicon-vitejs-plain colored"),
  Git: dev("devicon-git-plain colored"),
  GitHub: dev("devicon-github-plain"),
  Postman: dev("devicon-postman-plain colored"),
  Swagger: dev("devicon-swagger-plain colored"),
  "Visual Studio": dev("devicon-visualstudio-plain colored"),
  "VS Code": dev("devicon-vscode-plain colored"),
  "SQL Server Management Studio": dev("devicon-azuresqldatabase-plain colored"),
  "Redis Insight": dev("devicon-redis-plain colored"),

  // ---- project tech icons (react-icons) ----
  "Clean Architecture": reactIcon(FiLayers, "text-teal-700 dark:text-[#57f1db]"),
  CQRS: reactIcon(FiShuffle, "text-teal-700 dark:text-[#57f1db]"),
  MediatR: reactIcon(FiSend, "text-teal-700 dark:text-[#57f1db]"),
  SignalR: reactIcon(FiActivity, "text-teal-700 dark:text-[#57f1db]"),
  JWT: reactIcon(FiKey, "text-teal-700 dark:text-[#57f1db]"),
  FluentValidation: reactIcon(FiCheckCircle, "text-teal-700 dark:text-[#57f1db]"),
  Serilog: reactIcon(FiTerminal, "text-teal-700 dark:text-[#57f1db]"),
  "Material UI": reactIcon(SiMui, "text-[#007FFF] dark:text-[#64B5F6]"),
  "React Router": reactIcon(SiReactrouter, "text-[#CA4245] dark:text-[#E57373]"),
  Axios: reactIcon(SiAxios, "text-[#5A29E4] dark:text-[#9B7BFF]"),

  // ---- skill section overrides (react-icons) ----
  "JWT Authentication": reactIcon(FiKey, "text-2xl text-primary"),
  "Framer Motion": reactIcon(FiZap, "text-2xl text-primary"),
  Jotai: reactIcon(FiCircle, "text-2xl text-primary"),
  "CQRS / MediatR": reactIcon(FiShare2, "text-2xl text-primary"),
};

export const iconClassName = "transition-all";
export const techIconClassName = "h-8 w-8";
export const socialIconClassName =
  "text-lg grayscale transition-all duration-300 group-hover:grayscale-0";
export const iconContainerClassName =
  "flex h-10 w-10 items-center justify-center rounded-lg bg-slate-200 dark:bg-surface-highest";
